site_name: Slender
nav:
  - Home: index.md
  - Slender:
    - List: list.md
    - Set: set.md
    - Dictionary: dictionary.md

theme: readthedocs

markdown_extensions:
    - toc:
          permalink: "#"

collapse_navigation: true

